# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'firey_chat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for firey_chat
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'GoogleToolboxForMac'

  pod 'Firebase/AdMob'
  pod 'Firebase/Storage'
#  pod 'Firebase/Invites'
  pod 'Firebase/Analytics'
  
  pod 'Firebase/AppIndexing'
#  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/RemoteConfig'

  target 'firey_chatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
